# Generated by Django 4.0.2 on 2022-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=140)),
                ('isbn_number', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('language', models.CharField(max_length=140)),
                ('link_to_cover', models.CharField(max_length=140)),
            ],
        ),
    ]
