# Generated by Django 4.0.2 on 2022-02-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_public_date_alter_book_isbn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='book',
            name='link_to_cover',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='public_date',
            field=models.PositiveSmallIntegerField(blank=True, default=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
