# Generated by Django 4.0.2 on 2022-03-02 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn_number_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=140, validators=[django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='public_date',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
